/**
 * ROBOTS.TXT GENERATION
 * 
 * Next.js automatically generates robots.txt from this file.
 * 
 * WHAT IT DOES:
 * - Generates /robots.txt file for search engines
 * - Tells search engines which pages to crawl/index
 * - Specifies sitemap location
 * 
 * ROUTE: /robots.txt
 * 
 * CURRENT CONFIGURATION:
 * - Allows all user agents (*)
 * - Allows crawling of all pages (/)
 * - Disallows admin and API routes (/admin/, /api/)
 * - References sitemap location
 * 
 * WHY DISALLOW /api/?
 * - API routes shouldn't be indexed by search engines
 * - Prevents exposure of API endpoints
 * - Reduces unnecessary crawler requests
 * 
 * WHY DISALLOW /admin/?
 * - Admin pages are typically protected
 * - Shouldn't be indexed for security
 * - Keeps admin interface private
 * 
 * SITEMAP REFERENCE:
 * Points to /sitemap.xml (generated by app/sitemap.ts)
 * 
 * BASE URL:
 * Uses NEXT_PUBLIC_BASE_URL environment variable if set.
 * Falls back to http://localhost:3000 for development.
 * 
 * PRODUCTION:
 * Set NEXT_PUBLIC_BASE_URL in production environment:
 * NEXT_PUBLIC_BASE_URL=https://yourdomain.com
 * 
 * USAGE:
 * Search engines automatically fetch /robots.txt
 * No manual configuration needed.
 */

import { MetadataRoute } from 'next'

/**
 * ROBOTS.TXT GENERATOR FUNCTION
 * 
 * Generates robots.txt content for search engines.
 * 
 * @returns Robots configuration object
 * 
 * OUTPUT FORMAT:
 * ```
 * User-agent: *
 * Allow: /
 * Disallow: /admin/
 * Disallow: /api/
 * Sitemap: https://yourdomain.com/sitemap.xml
 * ```
 */
export default async function robots(): Promise<MetadataRoute.Robots> {
  /**
   * BASE URL DETERMINATION
   * 
   * Gets base URL from environment variable or defaults to localhost.
   * Used for sitemap reference in robots.txt.
   */
  const baseUrl = process.env.NEXT_PUBLIC_BASE_URL || 'http://localhost:3000'

  /**
   * ROBOTS.TXT CONFIGURATION
   * 
   * Defines what search engines can crawl.
   * 
   * RULES:
   * - userAgent: '*' means applies to all search engines
   * - allow: '/' means allow crawling all pages
   * - disallow: Array of paths to block from indexing
   * - sitemap: Location of sitemap.xml file
   */
  return {
    rules: {
      userAgent: '*', // Applies to all search engines (Google, Bing, etc.)
      allow: '/', // Allow crawling all pages
      disallow: ['/admin/', '/api/'], // Block admin and API routes from indexing
    },
    sitemap: `${baseUrl}/sitemap.xml`, // Reference to sitemap location
  }
}
